# Generated by Django 2.1.7 on 2019-03-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mshirinskiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act_Mikle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_on_instinct', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
