# Generated by Django 2.1.7 on 2019-03-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_subscribers1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers1',
            name='data',
        ),
    ]
