# Generated by Django 2.1.7 on 2019-03-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_subscribers2'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers2',
            name='article_imge',
            field=models.ImageField(blank=True, null=True, upload_to='sta  ', verbose_name='qe'),
        ),
    ]
