# Generated by Django 2.1.7 on 2019-03-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_subscribers2_article_imge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('article_imge', models.ImageField(blank=True, null=True, upload_to='media  ', verbose_name='ww.jpg')),
            ],
        ),
        migrations.AlterField(
            model_name='subscribers2',
            name='article_imge',
            field=models.ImageField(blank=True, null=True, upload_to='media  ', verbose_name='ww.jpg'),
        ),
    ]
